;             
CREATE USER IF NOT EXISTS SA SALT 'a42796261981560b' HASH 'c339987db178744727b25b2d8e5ce1132d86add1f6357e1911aa2d5248c180d6' ADMIN;           
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4F55921B_B0FF_457F_A403_F7C4BC11F752 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0E6011E3_CAED_4D40_A285_1E89BB5055F2 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9722D1D6_05DF_4CAE_89BA_073EC1F2FA8C START WITH 1 BELONGS_TO_TABLE;    
CREATE CACHED TABLE PUBLIC."schema_version"(
    "installed_rank" INT NOT NULL,
    "version" VARCHAR(50),
    "description" VARCHAR(200) NOT NULL,
    "type" VARCHAR(20) NOT NULL,
    "script" VARCHAR(1000) NOT NULL,
    "checksum" INT,
    "installed_by" VARCHAR(100) NOT NULL,
    "installed_on" TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "execution_time" INT NOT NULL,
    "success" BOOLEAN NOT NULL
);    
ALTER TABLE PUBLIC."schema_version" ADD CONSTRAINT PUBLIC."schema_version_pk" PRIMARY KEY("installed_rank");  
-- 1 +/- SELECT COUNT(*) FROM PUBLIC."schema_version";        
INSERT INTO PUBLIC."schema_version"("installed_rank", "version", "description", "type", "script", "checksum", "installed_by", "installed_on", "execution_time", "success") VALUES
(1, '1.1', 'init', 'SQL', 'V1_1__init.sql', -2120734098, 'SA', TIMESTAMP '2017-10-30 14:01:28.644', 10, TRUE);             
CREATE INDEX PUBLIC."schema_version_s_idx" ON PUBLIC."schema_version"("success");             
CREATE CACHED TABLE PUBLIC."ARTICLE-REPLY"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_0E6011E3_CAED_4D40_A285_1E89BB5055F2) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0E6011E3_CAED_4D40_A285_1E89BB5055F2,
    ARTICLE_ID INT DEFAULT NULL,
    NAME VARCHAR(60) DEFAULT NULL,
    EMAIL VARCHAR(60) DEFAULT NULL,
    CONTENT VARCHAR(5000) DEFAULT NULL,
    CREATE_TIME VARCHAR(30) DEFAULT NULL
); 
ALTER TABLE PUBLIC."ARTICLE-REPLY" ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(ID);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."ARTICLE-REPLY";         
CREATE CACHED TABLE PUBLIC.ARTICLE(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_9722D1D6_05DF_4CAE_89BA_073EC1F2FA8C) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9722D1D6_05DF_4CAE_89BA_073EC1F2FA8C,
    USER_ID INT DEFAULT NULL,
    TYPE INT DEFAULT NULL,
    TITLE VARCHAR(60) DEFAULT NULL,
    CONTENT TEXT DEFAULT NULL,
    CREATE_TIME VARCHAR(30) DEFAULT NULL,
    START_TIME VARCHAR(500) DEFAULT NULL,
    END_TIME VARCHAR(500) DEFAULT NULL
);         
ALTER TABLE PUBLIC.ARTICLE ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ARTICLE; 
CREATE CACHED TABLE PUBLIC.USERS(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_4F55921B_B0FF_457F_A403_F7C4BC11F752) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4F55921B_B0FF_457F_A403_F7C4BC11F752,
    USERNAME VARCHAR(255) DEFAULT NULL,
    USER_SEX VARCHAR(255) DEFAULT NULL,
    NICK_NAME VARCHAR(255) DEFAULT NULL,
    PASSWORD VARCHAR(255) DEFAULT NULL
);     
ALTER TABLE PUBLIC.USERS ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
